### ISSUE TITLE
[Packet error] Stack underflow at 169, Opcode: 0x0B

### ISSUE THREAD

**Issue by DanielLuu** [HypatiaOfAlexandria/MortalClient#2]
Error on Character listing. Not sure why. What's the best WZs to use for this?

**Comment by HypatiaOfAlexandria** [comment]
Well, if you're using [MortalMS](https://github.com/HypatiaOfAlexandria/MortalMS) then I will say that I gave up on using HeavenMS.

If you are having an error like this, then there is some match between the packet schema (with opcode `0x0b`) that the client is expecting and that the server is expecting. So you will want to investigate what the client is expecting: [https://github.com/HypatiaOfAlexandria/MortalClient/blob/master/Net/Handlers/LoginHandlers.cpp#L106](https://github.com/HypatiaOfAlexandria/MortalClient/blob/master/Net/Handlers/LoginHandlers.cpp#L106), and compare it to the corresponding code in your server source. For my old fork of MortalMS that's, uh: [https://github.com/HypatiaOfAlexandria/MortalMS/blob/81f444378c0f2b7d1e576a3f0f48b0d44b84e83c/src/tools/MaplePacketCreator.java#L893](https://github.com/HypatiaOfAlexandria/MortalMS/blob/81f444378c0f2b7d1e576a3f0f48b0d44b84e83c/src/tools/MaplePacketCreator.java#L893).

As far as "WZs" go, to quote the README:

> The client is intended to be quasi-conformant with GMS version 83. For the UI file (UI.nx), one from GMS version 154+ should be used.

Of course they can't actually be "WZs", they have to be [NX files](https://nxformat.github.io/). Additionally, the audio has to be in [Ogg Vorbis](https://en.wikipedia.org/wiki/Vorbis) format rather than MP3.

**Comment by bravuradluu** [comment]
@HypatiaOfAlexandria Thanks for the response. I ended up helping refactor HeavenClient to work with Mac. I'll keep an eye out for your work with rust though.

**Comment by DanielLuu** [comment]
@HypatiaOfAlexandria Ended up refactoring HeavenClient to work with mac. Looks like no open source client is ready for public play though tbh.

**Comment by HypatiaOfAlexandria** [comment]
> Looks like no open source client is ready for public play though tbh.

Yes... that's why there aren't any servers out there using open source clients. I will say that I have all but abandoned open source MapleStory as I have no faith in "the MapleStory community" in any way, shape, or form. I cynically suggest that you give up and just play ~~MapleRoyals~~ JoblessMS unless you want to dedicate all of your free time to reviving a flimsy MMORPG played by terrible people!

**Comment by DanielLuu** [comment]
@HypatiaOfAlexandria my goal is to Port one of these clients to JS using emscripten and host it using web assembly. Let me know if you're interested. You seem to have a lot of cmake knowledge which I severely lack.

**Comment by HypatiaOfAlexandria** [comment]
Uhm, no offense, but that doesn't sound like a great idea. If you do insist on doing FLOSS MapleStory work, I would focus on getting a working client, and nothing less. Porting to the web browser is pointless and will only tarnish the performance of the application, in addition to being a shit ton of work that could have gone towards actually making a nice client in the first place.
